# Run pipeline for MRs and main branch
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - lint

lint:
    stage: lint
    image: rust:1.93.1
    script:
        - rustc --version
        - cargo --version
        - rustup component add clippy
        - cargo clippy --features docs-only
    allow_failure: true
