# CONFIGURATION
default:
    image: "registry.gitlab.com/tangram-vision/oss/ci-oss/public-ci:latest"
    before_script:
        # Update rust in case the latest version isn't built into our docker image.
        - rustup update stable

# Run pipeline for MRs and main branch
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - lint
    - doc

##### ########## ########## ########## ########## #####
# TEST STAGE
# - [PASS REQ] runs all unit tests in the build
# - [PASS REQ] runs a lint checker over every piece of code

lint:
    stage: lint
    script:
        - rustc --version
        - cargo --version
        - cargo clippy  
